# Generated by Django 4.1.2 on 2022-11-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_comment_article_cateogry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cateogry',
            new_name='category',
        ),
    ]
